name: Run Examples Tests
on:
  workflow_dispatch:
  push:
    branches:
      - ft-tests-debug

jobs:
  test-examples:
    uses: ./.github/workflows/examples.yml
    with:
      working-directory: ./python
    secrets: inherit
